/**
 * Dev mock data — set NEXT_PUBLIC_DEV_MOCK=true in .env.local to skip LLM calls.
 * Rich dataset: 50+ per category, spread across 6 months.
 */

function d(m: string, day: number) {
  return `2025-${m.padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}

const BOOKS = [
  { title: "百年孤独", rating: 5, date: d("9", 3), comment: "马尔克斯构建了一个完整的宇宙" },
  { title: "卡拉马佐夫兄弟", rating: 5, date: d("9", 8) },
  { title: "小径分岔的花园", rating: 5, date: d("9", 12), comment: "博尔赫斯永远让人迷失" },
  { title: "局外人", rating: 4, date: d("9", 15) },
  { title: "1984", rating: 5, date: d("9", 19), comment: "每隔几年重读一次都有新体会" },
  { title: "人类简史", rating: 4, date: d("9", 22) },
  { title: "三体", rating: 5, date: d("9", 25), comment: "中国科幻的天花板" },
  { title: "挪威的森林", rating: 4, date: d("9", 28) },
  { title: "月亮与六便士", rating: 4, date: d("10", 2) },
  { title: "刀锋", rating: 4, date: d("10", 5), comment: "毛姆最被低估的作品" },
  { title: "黄金时代", rating: 5, date: d("10", 8) },
  { title: "围城", rating: 5, date: d("10", 11), comment: "钱钟书的毒舌真是绝了" },
  { title: "活着", rating: 5, date: d("10", 14) },
  { title: "平凡的世界", rating: 4, date: d("10", 17) },
  { title: "白夜行", rating: 5, date: d("10", 20), comment: "东野圭吾最好的一本" },
  { title: "嫌疑人X的献身", rating: 4, date: d("10", 23) },
  { title: "解忧杂货店", rating: 3, date: d("10", 26) },
  { title: "房思琪的初恋乐园", rating: 5, date: d("10", 29), comment: "看完沉默了很久" },
  { title: "鼠疫", rating: 4, date: d("11", 1) },
  { title: "异乡人", rating: 4, date: d("11", 3) },
  { title: "索拉里斯星", rating: 5, date: d("11", 6), comment: "莱姆的科幻哲学太深邃" },
  { title: "刺猬的优雅", rating: 4, date: d("11", 9) },
  { title: "不能承受的生命之轻", rating: 5, date: d("11", 12) },
  { title: "生命中不能承受之轻", rating: 5, date: d("11", 15), comment: "昆德拉把存在主义写成了情书" },
  { title: "悉达多", rating: 4, date: d("11", 18) },
  { title: "荒原狼", rating: 4, date: d("11", 21) },
  { title: "德米安", rating: 4, date: d("11", 24), comment: "黑塞总能击中迷茫的灵魂" },
  { title: "了不起的盖茨比", rating: 4, date: d("11", 27) },
  { title: "麦田里的守望者", rating: 3, date: d("11", 30) },
  { title: "在路上", rating: 3, date: d("12", 2) },
  { title: "海边的卡夫卡", rating: 4, date: d("12", 5) },
  { title: "且听风吟", rating: 3, date: d("12", 8) },
  { title: "国境以南太阳以西", rating: 4, date: d("12", 11), comment: "村上最被低估的小说" },
  { title: "世界尽头与冷酷仙境", rating: 5, date: d("12", 14) },
  { title: "窗边的小豆豆", rating: 3, date: d("12", 17) },
  { title: "小王子", rating: 4, date: d("12", 20) },
  { title: "瓦尔登湖", rating: 4, date: d("12", 23), comment: "梭罗的孤独是一种奢侈品" },
  { title: "枪炮、病菌与钢铁", rating: 4, date: d("12", 26) },
  { title: "思考快与慢", rating: 3, date: d("12", 29) },
  { title: "娱乐至死", rating: 4, date: "2026-01-02" },
  { title: "乌合之众", rating: 3, date: "2026-01-05" },
  { title: "置身事内", rating: 4, date: "2026-01-08", comment: "理解中国经济的入门必读" },
  { title: "芯片战争", rating: 4, date: "2026-01-11" },
  { title: "纳瓦尔宝典", rating: 3, date: "2026-01-14" },
  { title: "刻意练习", rating: 3, date: "2026-01-17" },
  { title: "当下的力量", rating: 4, date: "2026-01-20" },
  { title: "被讨厌的勇气", rating: 4, date: "2026-01-23", comment: "阿德勒心理学的最佳入门" },
  { title: "蛤蟆先生去看心理医生", rating: 3, date: "2026-01-26" },
  { title: "也许你该找个人聊聊", rating: 4, date: "2026-01-29" },
  { title: "非暴力沟通", rating: 3, date: "2026-02-01" },
  { title: "亲密关系", rating: 4, date: "2026-02-04" },
  { title: "自卑与超越", rating: 4, date: "2026-02-07" },
  { title: "心流", rating: 3, date: "2026-02-10" },
  { title: "金阁寺", rating: 5, date: "2026-02-13", comment: "三岛由纪夫的美学暴力" },
  { title: "人间失格", rating: 4, date: "2026-02-16" },
  { title: "罗生门", rating: 4, date: "2026-02-19" },
];

const MOVIES = [
  { title: "花样年华", rating: 5, date: d("9", 2), comment: "王家卫的镜头语言无人能及" },
  { title: "重庆森林", rating: 5, date: d("9", 5) },
  { title: "春光乍泄", rating: 5, date: d("9", 9) },
  { title: "2046", rating: 4, date: d("9", 13) },
  { title: "阿飞正传", rating: 4, date: d("9", 17) },
  { title: "银翼杀手2049", rating: 5, date: d("9", 20), comment: "维伦纽瓦把孤独拍成了史诗" },
  { title: "降临", rating: 5, date: d("9", 23) },
  { title: "沙丘", rating: 4, date: d("9", 26) },
  { title: "寄生虫", rating: 5, date: d("9", 29), comment: "奉俊昊天才般的阶级隐喻" },
  { title: "燃烧", rating: 5, date: d("10", 3) },
  { title: "小偷家族", rating: 5, date: d("10", 6) },
  { title: "无人知晓", rating: 4, date: d("10", 9) },
  { title: "步履不停", rating: 4, date: d("10", 12), comment: "是枝裕和最温柔的残酷" },
  { title: "海街日记", rating: 4, date: d("10", 15) },
  { title: "驾驶我的车", rating: 5, date: d("10", 18) },
  { title: "完美的日子", rating: 5, date: d("10", 21), comment: "文德斯拍出了孤独的美" },
  { title: "千与千寻", rating: 5, date: d("10", 24) },
  { title: "龙猫", rating: 4, date: d("10", 27) },
  { title: "天空之城", rating: 4, date: d("10", 30) },
  { title: "你的名字", rating: 4, date: d("11", 2) },
  { title: "铃芽之旅", rating: 3, date: d("11", 5) },
  { title: "攻壳机动队", rating: 5, date: d("11", 8), comment: "赛博朋克的圣经" },
  { title: "新世纪福音战士剧场版", rating: 5, date: d("11", 11) },
  { title: "阿基拉", rating: 4, date: d("11", 14) },
  { title: "星际穿越", rating: 5, date: d("11", 17) },
  { title: "盗梦空间", rating: 5, date: d("11", 20), comment: "诺兰最完美的叙事结构" },
  { title: "信条", rating: 3, date: d("11", 23) },
  { title: "搏击俱乐部", rating: 5, date: d("11", 26) },
  { title: "穆赫兰道", rating: 5, date: d("11", 29), comment: "林奇的迷宫让人上瘾" },
  { title: "双峰：与火同行", rating: 4, date: d("12", 2) },
  { title: "低俗小说", rating: 5, date: d("12", 5) },
  { title: "杀死比尔", rating: 4, date: d("12", 8) },
  { title: "老无所依", rating: 5, date: d("12", 11), comment: "科恩兄弟最冷的一部" },
  { title: "醉乡民谣", rating: 4, date: d("12", 14) },
  { title: "大空头", rating: 4, date: d("12", 17) },
  { title: "社交网络", rating: 5, date: d("12", 20) },
  { title: "消失的爱人", rating: 5, date: d("12", 23), comment: "芬奇对婚姻的终极解剖" },
  { title: "七宗罪", rating: 5, date: d("12", 26) },
  { title: "十二怒汉", rating: 5, date: d("12", 29) },
  { title: "肖申克的救赎", rating: 5, date: "2026-01-01" },
  { title: "教父", rating: 5, date: "2026-01-04" },
  { title: "美丽人生", rating: 5, date: "2026-01-07", comment: "笑着看完然后哭了" },
  { title: "楚门的世界", rating: 5, date: "2026-01-10" },
  { title: "闪灵", rating: 4, date: "2026-01-13" },
  { title: "2001太空漫游", rating: 5, date: "2026-01-16", comment: "库布里克的终极浪漫" },
  { title: "发条橙", rating: 4, date: "2026-01-19" },
  { title: "东京物语", rating: 5, date: "2026-01-22" },
  { title: "晚春", rating: 4, date: "2026-01-25" },
  { title: "瀑布", rating: 4, date: "2026-01-28" },
  { title: "世界上最糟糕的人", rating: 4, date: "2026-02-02", comment: "北欧版的弗朗西斯·哈" },
  { title: "坠落的审判", rating: 5, date: "2026-02-05" },
  { title: "利益区域", rating: 4, date: "2026-02-08" },
  { title: "可怜的东西", rating: 4, date: "2026-02-11" },
  { title: "过往人生", rating: 5, date: "2026-02-14", comment: "一部关于因缘的电影，看完沉默了很久" },
  { title: "芭比", rating: 3, date: "2026-02-17" },
  { title: "奥本海默", rating: 5, date: "2026-02-20" },
];

const MUSIC = [
  { title: "OK Computer - Radiohead", rating: 5, date: d("9", 1), comment: "每一首都是焦虑的完美结晶" },
  { title: "Kid A - Radiohead", rating: 5, date: d("9", 4) },
  { title: "In Rainbows - Radiohead", rating: 5, date: d("9", 7) },
  { title: "Blonde - Frank Ocean", rating: 5, date: d("9", 10), comment: "深夜必听的灵魂私语" },
  { title: "Channel Orange - Frank Ocean", rating: 5, date: d("9", 14) },
  { title: "To Pimp a Butterfly - Kendrick Lamar", rating: 5, date: d("9", 18) },
  { title: "DAMN. - Kendrick Lamar", rating: 4, date: d("9", 22) },
  { title: "good kid, m.A.A.d city - Kendrick Lamar", rating: 5, date: d("9", 26) },
  { title: "Loveless - My Bloody Valentine", rating: 5, date: d("9", 30), comment: "噪音墙后面藏着最温柔的东西" },
  { title: "The Dark Side of the Moon - Pink Floyd", rating: 5, date: d("10", 3) },
  { title: "Wish You Were Here - Pink Floyd", rating: 5, date: d("10", 6) },
  { title: "The Wall - Pink Floyd", rating: 4, date: d("10", 9) },
  { title: "无条件 - 陈奕迅", rating: 4, date: d("10", 12) },
  { title: "不如不见 - 陈奕迅", rating: 4, date: d("10", 15) },
  { title: "K歌之王 - 陈奕迅", rating: 4, date: d("10", 18) },
  { title: "十年 - 陈奕迅", rating: 5, date: d("10", 21), comment: "粤语歌的情感浓度就是不一样" },
  { title: "富士山下 - 陈奕迅", rating: 5, date: d("10", 24) },
  { title: "New Boy - 朴树", rating: 4, date: d("10", 27) },
  { title: "平凡之路 - 朴树", rating: 4, date: d("10", 30) },
  { title: "那些花儿 - 朴树", rating: 5, date: d("11", 2), comment: "每次听都回到某个夏天" },
  { title: "生如夏花 - 朴树", rating: 5, date: d("11", 5) },
  { title: "春风十里 - 鹿先森乐队", rating: 3, date: d("11", 8) },
  { title: "南山南 - 马頔", rating: 3, date: d("11", 11) },
  { title: "成都 - 赵雷", rating: 3, date: d("11", 14) },
  { title: "For Emma, Forever Ago - Bon Iver", rating: 5, date: d("11", 17), comment: "小木屋里录出来的孤独" },
  { title: "22, A Million - Bon Iver", rating: 4, date: d("11", 20) },
  { title: "Carrie & Lowell - Sufjan Stevens", rating: 5, date: d("11", 23) },
  { title: "Illinois - Sufjan Stevens", rating: 4, date: d("11", 26) },
  { title: "Funeral - Arcade Fire", rating: 5, date: d("11", 29), comment: "每一个音符都在呐喊" },
  { title: "The Suburbs - Arcade Fire", rating: 4, date: d("12", 2) },
  { title: "Is This It - The Strokes", rating: 4, date: d("12", 5) },
  { title: "Whatever People Say - Arctic Monkeys", rating: 4, date: d("12", 8) },
  { title: "AM - Arctic Monkeys", rating: 4, date: d("12", 11) },
  { title: "Hozier - Hozier", rating: 4, date: d("12", 14), comment: "Take Me to Church 循环了一百遍" },
  { title: "Norman Fucking Rockwell - Lana Del Rey", rating: 5, date: d("12", 17) },
  { title: "Ultraviolence - Lana Del Rey", rating: 4, date: d("12", 20) },
  { title: "Melodrama - Lorde", rating: 5, date: d("12", 23), comment: "Z世代的情感圣经" },
  { title: "Pure Heroine - Lorde", rating: 4, date: d("12", 26) },
  { title: "After Hours - The Weeknd", rating: 4, date: d("12", 29) },
  { title: "Punisher - Phoebe Bridgers", rating: 5, date: "2026-01-02" },
  { title: "Stranger in the Alps - Phoebe Bridgers", rating: 4, date: "2026-01-05" },
  { title: "SOUR - Olivia Rodrigo", rating: 3, date: "2026-01-08" },
  { title: "Midnights - Taylor Swift", rating: 3, date: "2026-01-11" },
  { title: "folklore - Taylor Swift", rating: 4, date: "2026-01-14", comment: "Taylor 最好的一张 不接受反驳" },
  { title: "evermore - Taylor Swift", rating: 4, date: "2026-01-17" },
  { title: "Dummy - Portishead", rating: 5, date: "2026-01-20" },
  { title: "Mezzanine - Massive Attack", rating: 5, date: "2026-01-23", comment: "Trip-hop 的黑暗圣殿" },
  { title: "Homogenic - Björk", rating: 5, date: "2026-01-26" },
  { title: "Vespertine - Björk", rating: 5, date: "2026-01-29" },
  { title: "Currents - Tame Impala", rating: 4, date: "2026-02-01" },
  { title: "Lonerism - Tame Impala", rating: 5, date: "2026-02-04", comment: "迷幻摇滚的当代巅峰" },
  { title: "Grace - Jeff Buckley", rating: 5, date: "2026-02-07" },
  { title: "Either/Or - Elliott Smith", rating: 5, date: "2026-02-10" },
  { title: "Figure 8 - Elliott Smith", rating: 4, date: "2026-02-13" },
  { title: "The Glow Pt. 2 - The Microphones", rating: 5, date: "2026-02-16", comment: "lo-fi 的终极形态" },
  { title: "In the Aeroplane - Neutral Milk Hotel", rating: 5, date: "2026-02-19" },
];

const REVIEWS = [
  { title: "百年孤独", content: "马尔克斯不是在写小说，是在创世。每一个布恩迪亚都是人类孤独的一种变体。读完之后你会发现，原来孤独不是一种状态，而是一种宿命。第一次读的时候被那个循环的家族史震撼到说不出话，重读的时候才发现每个细节都是伏笔。", type: "book", rating: 5 },
  { title: "花样年华", content: "王家卫用这部电影证明了一件事：最好的爱情片不需要吻戏。梁朝伟和张曼玉的每一次擦肩而过都比任何激情戏更撩人。那个时钟、那条走廊、那件旗袍——所有的道具都在替角色说出他们永远不会说出口的话。", type: "movie", rating: 5 },
  { title: "OK Computer", content: "1997年Radiohead预言了我们2025年的焦虑。Paranoid Android里那段从温柔到暴烈的转换，就是我每天上班的心理曲线。这张专辑不是音乐，是一份精神诊断报告。", type: "music", rating: 5 },
  { title: "寄生虫", content: "奉俊昊最厉害的地方在于他让你同时同情两个阶级。地下室那场戏之后，电影的走向完全不可预测。看完之后你会开始注意身边那些你从来没注意过的气味。", type: "movie", rating: 5 },
  { title: "三体", content: "刘慈欣把宇宙写成了一个黑暗森林，然后你发现人类文明不过是森林里的一只萤火虫。黑暗森林法则是我读过的最令人不寒而栗的科幻设定，因为它太合理了。", type: "book", rating: 5 },
  { title: "Blonde", content: "Frank Ocean用这张专辑证明了R&B可以是最私密的艺术形式。每首歌都像是在偷听一个人深夜的自言自语。Nights那首歌中间的beat switch是音乐史上最美的转折之一。", type: "music", rating: 5 },
];

const DIARIES = [
  { title: "又是失眠的一夜", content: "凌晨三点还在刷豆瓣，看完了一个完全陌生的人的影评主页。他给每部文艺片都打了五星，短评写得比我的日记还长。突然觉得这个世界上一定有很多和我一样的人，在深夜里用别人的故事填充自己的空虚。", date: d("10", 15) },
  { title: "书店偶遇", content: "今天在单向街书店翻到了一本博尔赫斯的诗集，随手翻开的那一页写着「我用什么才能留住你」。站在书架前读完了整首诗，旁边有个女生也在看博尔赫斯。我们对视了一眼，然后各自走开了。这大概就是INFJ的社交方式。", date: d("11", 8) },
  { title: "重看花样年华", content: "第四次看花样年华了。这次注意到一个以前没发现的细节：周慕云和苏丽珍每次在楼梯间相遇，背景音乐都会变。王家卫是真的在用音乐讲述时间的流逝。突然理解了为什么有人说这是一部关于遗憾的电影——不是因为他们没有在一起，而是因为他们本可以。", date: d("12", 1) },
  { title: "年终书单", content: "今年读了五十多本书，回头看发现有一个明显的趋势：上半年读的都是小说，下半年开始转向非虚构和心理学。可能是因为虚构的世界待久了，开始想了解真实的自己。明年打算读更多哲学类的书，从叔本华开始。", date: d("12", 28) },
  { title: "Spotify年度报告", content: "Spotify说我今年听了4万分钟的音乐，最多的类型是indie rock和trip-hop。深夜听歌最多的时段是凌晨1-3点。Top artist是Radiohead，听了387次。我觉得这比任何MBTI测试都更能说明我是什么样的人。", date: "2026-01-05" },
];

const STATUSES = [
  { content: "看完燃烧之后在沙发上坐了半小时没动。李沧东到底是怎么做到让你在两个半小时里一直提着心的。", date: d("9", 30) },
  { content: "今天听了一整天的Radiohead，同事问我是不是失恋了。我说没有，我只是在思考存在的意义。他说那比失恋更可怕。", date: d("10", 10) },
  { content: "重读卡拉马佐夫兄弟，宗教大法官那一章读了三遍还是觉得不够。陀思妥耶夫斯基是真正的心理学家。", date: d("11", 5) },
  { content: "深夜在豆瓣上给一部2003年的冷门法国电影写了800字的影评。点赞数：0。但我觉得很满足。", date: d("11", 20) },
  { content: "今天有人问我推荐一部电影，我说了花样年华。对方说没听过。我说那你看过什么电影。对方说速度与激情。我微笑着结束了对话。", date: d("12", 3) },
  { content: "每次有人说「你看的东西好小众」的时候，我都不知道该高兴还是难过。", date: d("12", 15) },
  { content: "书架又满了。但我舍不得扔掉任何一本。每本书都像是某个时期的自己。", date: "2026-01-10" },
  { content: "年度最佳观影体验：一个人去看完美的日子。电影散场后在影院门口站了十分钟，看着来来往往的人，突然觉得孤独也可以很美。", date: "2026-01-20" },
  { content: "朋友圈越来越安静了。不是没话说，是越来越觉得有些感受只适合写在日记里。", date: "2026-02-01" },
  { content: "刚听完Elliott Smith的Either/Or，突然很想给十年前的自己写一封信。", date: "2026-02-12" },
];

export const MOCK_ANALYZE = {
  id: "mock-001",
  createdAt: new Date().toISOString(),
  doubanName: "内测用户",
  mbti: {
    type: "INFJ",
    title: "孤独的灵魂考古者",
    dimensions: {
      ie: { letter: "I", score: 72, evidence: "偏爱独处式的文艺消费，深夜刷片、安静读书是你的精神充电方式" },
      ns: { letter: "N", score: 81, evidence: "你的片单和书架都指向一个方向：抽象、隐喻、多重解读" },
      tf: { letter: "F", score: 65, evidence: "虽然你看推理片，但最后打动你的永远是角色的情感弧光" },
      jp: { letter: "J", score: 58, evidence: "你有自己的品味体系，但偶尔也会被一部意外的佳作打破计划" },
    },
    summary: "你的品味像一座私人博物馆——每件藏品都经过精心挑选，陈列着你对世界的理解。你不追热门，但你追的东西往往在几年后变成经典。",
  },
  roast: "你的豆瓣主页就是一部《我很有品味但我不说》的默片。书架上全是让人望而生畏的大部头，片单里一半是没人听过的小众片，音乐品味更是像在参加一场只有你一个人的音乐节。恭喜你，你是文化荒漠里最孤独的绿洲。",
  radarData: { wenqing: 88, emo: 76, shekong: 82, kaogu: 61, shangtou: 73 },
  summary: "一个被文字和光影喂养长大的灵魂，在文青浓度和社恐值上远超同龄人，但偶尔也该走出舒适区看看烂片，毕竟生活不只是艺术。",
  isPremium: false,
  input: {
    doubanId: "mock-user",
    doubanName: "内测用户",
    books: BOOKS,
    movies: MOVIES,
    music: MUSIC,
    reviews: REVIEWS,
    diaries: DIARIES,
    statuses: STATUSES,
    source: "douban" as const,
  },
  sampleCount: BOOKS.length + MOVIES.length + MUSIC.length,
  realCounts: { books: BOOKS.length, movies: MOVIES.length, music: MUSIC.length },
  bookCount: BOOKS.length,
  movieCount: MOVIES.length,
  musicCount: MUSIC.length,
  itemCount: BOOKS.length + MOVIES.length + MUSIC.length,
};

export const MOCK_EXPAND = {
  bookAnalysis:
    "一盏台灯下，你的书架像一面棱镜，折射出你灵魂深处对秩序与混沌的双重迷恋。马尔克斯的魔幻现实是你的精神故乡——你相信现实比虚构更荒诞，所以你选择在虚构中寻找真实。博尔赫斯的迷宫是你的思维游乐场，你在无限分岔的路径中获得别人在过山车上才有的快感。从卡拉马佐夫兄弟到被讨厌的勇气，你的阅读轨迹暴露了一个典型INFJ的灵魂进化路线：先用文学确认自己的孤独，再用心理学尝试和解。村上春树是你偶尔放纵的甜品，你知道它没有陀思妥耶夫斯基那么沉重，但你需要那种温柔的忧伤来平衡灵魂的重量。你的书架不是图书馆，是一部自传。",
  movieAnalysis:
    "暗下来的影院是你最安全的藏身之所。王家卫的氤氲镜头是你的情感母语——那些欲言又止的凝视、擦肩而过的遗憾，你在银幕上看到自己不敢在现实中表达的一切。维伦纽瓦的宏大叙事满足了你对未知世界的渴望，你在赛博朋克的废墟里看到了人类最本质的孤独。从攻壳机动队到2001太空漫游，你的科幻片单暴露了你真正害怕的东西：不是未来，而是人类在未来的意义。是枝裕和和小津安二郎是你的情感避风港，在那里日常生活的温度刚好够融化你INFJ外壳下的冰。奉俊昊和大卫·芬奇满足了你对秩序的渴望——你喜欢看精密的叙事机器运转，因为这让你觉得混乱的世界也可以被理解。你的片单是一封写给孤独的情书。",
  musicAnalysis:
    "深夜两点的耳机里，你的世界只剩下声波和呼吸。Radiohead是你焦虑的外化——你在Thom Yorke的颤抖中听到自己午夜三点的心跳，三张专辑循环播放就是你的精神年轮。Frank Ocean的温柔是你藏在冷漠外壳下的秘密花园，Blonde和Channel Orange之间的距离就是你从青春到成熟的距离。从朴树到陈奕迅，你的华语歌单是一部90后的情感编年史——New Boy是你曾经相信的未来，平凡之路是你现在接受的现实。Elliott Smith和Phoebe Bridgers的lo-fi忧伤是你最私密的角落，你在那些几乎听不清的低语里找到了一种被理解的错觉。你的歌单不是音乐，是一本用声波写成的日记。凌晨三点的循环播放就是你和自己对话的方式。",
  timelineMonths: [
    {
      month: "2025-09",
      books: ["百年孤独", "卡拉马佐夫兄弟", "小径分岔的花园", "1984", "三体", "挪威的森林"],
      movies: ["花样年华", "重庆森林", "春光乍泄", "银翼杀手2049", "降临", "寄生虫"],
      music: ["OK Computer", "Blonde", "To Pimp a Butterfly", "Loveless"],
      mood: "文艺大爆发期，品味浓度拉满",
      moodScore: 42,
      tasteShift: "九月是你的文艺觉醒月，一口气吃了六个月的精神粮食",
      roast: "九月的你活在平行宇宙里，现实世界请留言",
    },
    {
      month: "2025-10",
      books: ["月亮与六便士", "围城", "白夜行", "房思琪的初恋乐园"],
      movies: ["燃烧", "小偷家族", "驾驶我的车", "完美的日子", "千与千寻"],
      music: ["Dark Side of the Moon", "陈奕迅", "朴树"],
      mood: "从宏大叙事转向人间细节",
      moodScore: 55,
      tasteShift: "开始从纯文学下沉到日本电影和华语民谣，品味在软化",
      roast: "看完房思琪又看小偷家族，你是在做年度最虐心马拉松吗",
    },
    {
      month: "2025-11",
      books: ["索拉里斯星", "不能承受的生命之轻", "德米安", "荒原狼"],
      movies: ["攻壳机动队", "星际穿越", "盗梦空间", "搏击俱乐部", "穆赫兰道"],
      music: ["Bon Iver", "Sufjan Stevens", "Arcade Fire"],
      mood: "存在主义危机高峰期",
      moodScore: 28,
      tasteShift: "品味能量降到谷底但深度达到巅峰，黑塞+昆德拉+林奇的组合拳",
      roast: "十一月的你像是在读一个哲学系研究生的必读书单，你确定你不是在写论文？",
    },
    {
      month: "2025-12",
      books: ["海边的卡夫卡", "世界尽头与冷酷仙境", "瓦尔登湖"],
      movies: ["低俗小说", "老无所依", "消失的爱人", "七宗罪", "社交网络"],
      music: ["Lana Del Rey", "Lorde", "Arctic Monkeys", "Hozier"],
      mood: "在孤独中寻找浪漫",
      moodScore: 48,
      tasteShift: "电影品味突然硬核化，音乐却在变温柔——你在用声音治愈画面带来的冲击",
      roast: "十二月你一边看大卫芬奇一边听Lorde，精神分裂程度满分",
    },
    {
      month: "2026-01",
      books: ["娱乐至死", "置身事内", "被讨厌的勇气", "蛤蟆先生去看心理医生"],
      movies: ["肖申克的救赎", "美丽人生", "2001太空漫游", "东京物语"],
      music: ["Phoebe Bridgers", "Taylor Swift folklore", "Portishead", "Massive Attack", "Bjork"],
      mood: "从文艺青年转型为焦虑中年",
      moodScore: 62,
      tasteShift: "阅读从小说转向非虚构和心理自助，你的INFJ自我探索正式启动",
      roast: "一月你终于开始看心理学了——恭喜你，文艺片看多了终于决定正视自己的问题",
    },
    {
      month: "2026-02",
      books: ["金阁寺", "人间失格", "罗生门"],
      movies: ["坠落的审判", "过往人生", "奥本海默"],
      music: ["Tame Impala", "Elliott Smith", "Neutral Milk Hotel"],
      mood: "日本文学的毁灭美学与独立音乐的废墟浪漫",
      moodScore: 38,
      tasteShift: "从心理学回到文学，但这次选的是最极端的三岛和太宰——你的灵魂需要烈酒",
      roast: "二月读人间失格听Elliott Smith，你的心理咨询师知道吗？",
    },
  ],
  timelineText:
    "你的品味轨迹像一条深海潜水曲线——九月和十一月分别探到两个低点，一月短暂上浮之后二月又潜下去了。你的消费模式暴露了一个典型INFJ的循环：积累压力→通过高强度文艺消费释放→短暂回归日常→再次下潜。你的书影音不是娱乐，是你的情绪调节系统。\n\n下个月你可能会突然迷上一部轻松的喜剧或者一张电子专辑——不是因为你变肤浅了，而是你的灵魂需要喘口气。建议试试韦斯安德森或者Tame Impala的新专辑。",
};

export const MOCK_SHARE_UNLOCK = {
  crossDomain:
    "你的书影音之间有一条隐秘的红线：孤独。百年孤独的布恩迪亚家族、花样年华里错过的梁朝伟和张曼玉、Frank Ocean在Blonde里的低语、Elliott Smith几乎听不清的呢喃——它们都在讲述同一个故事：人与人之间那道无法跨越的距离。你的评论和日记进一步证实了这一点：你在深夜写长评、独自去影院、用音乐填充凌晨三点的空白。你被这个主题反复吸引，不是因为你享受孤独，而是因为你想确认：这种感觉是不是只有你有。答案是——当然不是，但你的品味让你的孤独变得格外精致。",
  personality:
    "作为一个INFJ，你的品味暴露了一个矛盾的灵魂：你渴望深度连接，却总是选择独处。56本书、56部电影、56首音乐——你的年消费量说明你不缺时间，你缺的是一个能和你聊博尔赫斯的人。你的书架从马尔克斯到被讨厌的勇气，电影从王家卫到大卫芬奇，音乐从Radiohead到Elliott Smith——这条轨迹画出了一个从「确认孤独」到「接受孤独」再到「享受孤独」的完整弧线。你在生活中可能是那个「看起来很好但其实想很多」的人。你的焦虑来自于对意义的执着追问，你的渴望是被真正理解而不是被表面认可。凌晨三点听歌写日记的你，比白天上班的你更真实。你的品味是你的盔甲，也是你的软肋——它让你与众不同，也让你更加孤独。但说真的，一个能同时欣赏陀思妥耶夫斯基和Taylor Swift folklore的人，灵魂一定足够辽阔。",
  blindSpots:
    "你的品味地图上有几大片空白：喜剧、动作片、偶像剧、嘻哈、电子舞曲。作为INFJ，你本能地觉得轻松的东西「不够深刻」，但韦斯安德森的喜剧比很多文艺片更有层次。试试看《布达佩斯大饭店》、听一张Daft Punk的Random Access Memories、读一本《银河系搭便车指南》——你可能会发现：浅不代表没有深度，严肃也不代表就是高级。你的emo指数76分，建议适当摄入一些快乐因子。",
  recommendations: [
    { title: "索拉里斯星", type: "book", reason: "作为INFJ，你会在莱姆的科幻哲学中找到灵魂共振——这本书问的问题和你每晚问自己的一模一样", matchScore: 95, alreadyConsumed: false },
    { title: "银河系搭便车指南", type: "book", reason: "你的书架太沉重了，需要一剂英式幽默来解毒。这本书会教你生命的终极答案是42", matchScore: 78, alreadyConsumed: false },
    { title: "完美的日子", type: "movie", reason: "维姆文德斯拍了一部关于孤独之美的电影，每一帧都像是为INFJ定制的冥想", matchScore: 92, alreadyConsumed: false },
    { title: "布达佩斯大饭店", type: "movie", reason: "韦斯安德森的对称构图和粉色幽默会打开你品味的一个新维度，相信我", matchScore: 82, alreadyConsumed: false },
    { title: "For Emma, Forever Ago", type: "music", reason: "Bon Iver在小木屋里录的这张专辑，是你冬夜灵魂的完美配乐", matchScore: 90, alreadyConsumed: false },
    { title: "Random Access Memories", type: "music", reason: "Daft Punk用复古未来主义证明了电子乐也可以有灵魂，你的品味需要这个", matchScore: 75, alreadyConsumed: false },
    { title: "刺猬的优雅", type: "book", reason: "一个门房老太太的内心独白，你会在她的孤独和骄傲中看到自己的影子", matchScore: 87, alreadyConsumed: false },
    { title: "之后的我们", type: "movie", reason: "岩井俊二的光影诗学遇上中国式的错过，是你的审美舒适区", matchScore: 84, alreadyConsumed: false },
    { title: "Vespertine", type: "music", reason: "Bjork用冰岛的寒冷创造了最温暖的电子乐，适合你凌晨两点的耳机时间", matchScore: 88, alreadyConsumed: false },
    { title: "春物语", type: "movie", reason: "相米慎二被低估的杰作，一个INFJ女高中生的内心世界", matchScore: 80, alreadyConsumed: false },
  ],
};
